### ISSUE TITLE
Application Conflict in All History stuff

### ISSUE THREAD

**Issue by harles09** [Hanifan12/Food-Calories#1]
in History Adapter, Fragment, and ViewModel. I Have Conflict Code, Gradle build or something missing and when I wanna pull into github in last 2 pull I got conflict message. Please Fix It
my Gradle
classpath 'com.android.tools.build:gradle:7.1.0-alpha01'
classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32'
classpath 'com.google.gms:google-services:4.3.8'
classpath 'com.google.firebase:perf-plugin:1.4.0'

in this implementation, I have missed something
implementation 'androidx.preference:preference:1.1.1'

implementation for Core Ktx i use 
implementation 'androidx.core:core-ktx:1.5.0'

Gradle JDK I use
11 Java Version "11.0.8" Canary

if in the future we got another error like this I suggest changing updates from Cannary channel to Stable channel

Thanks for reading this
Haryo Bimo.

**Comment by fortoszone** [comment]
fixed for now 80c97ddb6930d5101cdb4415ddb7213deae00ff7
